const webGlobals = {
    AbortController: 'readonly',
    console: 'readonly',
    crypto: 'readonly',
    document: 'readonly',
    fetch: 'readonly',
    localStorage: 'readonly',
    requestAnimationFrame: 'readonly',
    Request: 'readonly',
    Response: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    TextEncoder: 'readonly',
    TextDecoder: 'readonly',
};

export default [
    {
        ignores: ['.wrangler/**', 'coverage/**', 'node_modules/**'],
    },
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            globals: webGlobals,
            sourceType: 'module',
        },
        rules: {
            'constructor-super': 'error',
            eqeqeq: 'error',
            'for-direction': 'error',
            'getter-return': 'error',
            'no-async-promise-executor': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-fallthrough': 'error',
            'no-import-assign': 'error',
            'no-loss-of-precision': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-obj-calls': 'error',
            'no-promise-executor-return': 'error',
            'no-redeclare': 'error',
            'no-self-assign': 'error',
            'no-setter-return': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-this-before-super': 'error',
            'no-undef': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'no-unreachable-loop': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-labels': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
            'no-useless-backreference': 'error',
            'no-useless-catch': 'error',
            'no-useless-escape': 'error',
            'no-with': 'error',
            'object-shorthand': 'error',
            'prefer-const': 'error',
            'require-yield': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
        },
    },
];
